//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringsOperations.ConsoleClient.StringsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringsService.IStringsService")]
    public interface IStringsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/NumberOfContains", ReplyAction="http://tempuri.org/IStringsService/NumberOfContainsResponse")]
        int NumberOfContains(string subString, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/NumberOfContains", ReplyAction="http://tempuri.org/IStringsService/NumberOfContainsResponse")]
        System.Threading.Tasks.Task<int> NumberOfContainsAsync(string subString, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringsServiceChannel : StringsOperations.ConsoleClient.StringsService.IStringsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringsServiceClient : System.ServiceModel.ClientBase<StringsOperations.ConsoleClient.StringsService.IStringsService>, StringsOperations.ConsoleClient.StringsService.IStringsService {
        
        public StringsServiceClient() {
        }
        
        public StringsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NumberOfContains(string subString, string text) {
            return base.Channel.NumberOfContains(subString, text);
        }
        
        public System.Threading.Tasks.Task<int> NumberOfContainsAsync(string subString, string text) {
            return base.Channel.NumberOfContainsAsync(subString, text);
        }
    }
}
